"""huoh

Revision ID: 2892de1c6faf
Revises: c49eb0e794f1
Create Date: 2020-02-08 22:08:59.849875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2892de1c6faf'
down_revision = 'c49eb0e794f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('plandate', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'plandate')
    # ### end Alembic commands ###
