"""migrate

Revision ID: 505287d37590
Revises: 
Create Date: 2020-01-24 18:14:15.801031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505287d37590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('street', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('street', 'date_modified')
    # ### end Alembic commands ###
