"""huoh

Revision ID: c49eb0e794f1
Revises: 7113ede7a1b7
Create Date: 2020-02-08 22:06:38.815536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49eb0e794f1'
down_revision = '7113ede7a1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('plandate', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'plandate')
    # ### end Alembic commands ###
